### ISSUE TITLE
Falha ao alterar senha

### ISSUE THREAD

**Issue by henrybezerrra** [jaelson13/FindMobile#5]
Esta dando como senha incorreta
![screenshot_20171026-170732 1](https://user-images.githubusercontent.com/23055245/32074610-55b48e76-ba70-11e7-9005-c8a36f9cca5e.png)

**Comment by cabalbarreto** [comment]
Cara é froide, como o sr. coloca um erro sem especificar com clareza que tipo de erro, que dados foram inseridos e se há ou não comunicação efetiva com a aplicação? Este é um dos vários problemas que temos com o teste!
